# ~/.config/hypr/hyprlock.conf

$font = FantasqueSansMono

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%

    outline_thickness = 0
    outer_color = rgba(00000000)
    inner_color = rgba(00000000)

    font_family = $font
    font_color = rgb(143, 143, 143)
    placeholder_text = $USER

    check_color = rgba(00ff99ee)
    check_text = ✓

    fail_color = rgba(ff3366ee)
    fail_text = ✗

    dots_spacing = 0.3
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

# TIME (12-hour)
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    font_size = 24
    font_family = $font

    position = -30, -20
    halign = right
    valign = top
}

# DATE (smaller)
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 18
    font_family = $font

    position = -30, -60
    halign = right
    valign = top
}
